pushword_media:
  path: /media/{path} #todo injecting pw.public_media_dir
  controller: Pushword\Core\Controller\MediaController::download
  methods: [GET, HEAD]
  requirements:
    path: '[a-zA-Z0-9\-/\.]*'
