pushword_page_sitemap:
  path: /{_locale}sitemap.{_format}
  controller: Pushword\Core\Controller\PageController::showSitemap
  methods: [GET, HEAD]
  requirements:
    _locale: '[a-zA-Z]{2}(_[a-zA-Z]+)?\/|'
    _format: 'xml|txt'

pushword_page_main_feed:
  path: /{_locale}feed.xml
  controller: Pushword\Core\Controller\PageController::showMainFeed
  methods: [GET, HEAD]
  requirements:
    _locale: '[a-zA-Z]{2}(_[a-zA-Z]+)?\/|'

pushword_page_robots_txt:
  path: /{_locale}robots.txt
  controller: Pushword\Core\Controller\PageController::showRobotsTxt
  methods: [GET, HEAD]
  requirements:
    _locale: '[a-zA-Z]{2}(_[a-zA-Z]+)?\/|'

pushword_page_feed:
  path: /{slug}.xml
  controller: Pushword\Core\Controller\PageController::showFeed
  methods: [GET, HEAD]
  requirements:
    slug: '[A-Za-z0-9_\/\.\-]*'
# todo : add priority to this route https://symfony.com/doc/current/routing.html#priority-parameter
# move routes to annotation ?!
# permit to use extension without bug with this catch all
