framework:
  secret: "secretKeyToOverride (normally, it s automatically done by symfony standard edition"

  session:
    cookie_lifetime: 0
    handler_id: "file://%kernel.project_dir%/var/sessions"

  php_errors:
    log: true

  assets:
    json_manifest_path: "%kernel.project_dir%/public/assets/manifest.json"

  http_method_override: false
