framework:
  secret: "secretKeyToOverride (normally, it s automatically done by symfony standard edition"

  session:
    handler_id: ~
    cookie_lifetime: 0

  php_errors:
    log: true

  assets:
    json_manifest_path: "%kernel.project_dir%/public/assets/manifest.json"
