vich_uploader:
  db_driver: orm

  mappings:
    media_media:
      #uri_prefix:
      upload_destination: '%pw.media_dir%'
      namer:
        service: Vich\UploaderBundle\Naming\PropertyNamer #Pushword\Core\Service\VichUploadPropertyNamer
        options: { property: 'slug' }
