imports:
  - { resource: '../../../src/Resources/config/services/all.yaml' }
  - { resource: '../../../src/Component/Router/RouterServices.yaml' }
  - { resource: '../../../src/Component/Filter/FilterServices.yaml' }
  - { resource: '../../../src/Component/App/services.yaml' }
